name = "FEAST"
uuid = "fb02c795-5df5-4db3-94bf-d2cc9bf113f2"
authors = ["Subhajit Kar <subhajitkar19@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
