# GitHub Pages configuration for FEAST.jl documentation

# Site settings
title: FEAST.jl Documentation
description: Fast Eigenvalue Algorithm using Spectral Transformations in Julia
baseurl: "/FEAST.jl" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # the base hostname & protocol for your site

# Repository settings
repository: your-username/FEAST.jl
repository_tree: main

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme (for GitHub Pages compatibility)
theme: minima

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - .github/

# Include in processing
include:
  - .htaccess

# SEO settings
lang: en_US
author:
  name: FEAST.jl Contributors
  email: feast-julia@example.com

social:
  - platform: github
    user_url: "https://github.com/your-username/FEAST.jl"
  - platform: julia
    user_url: "https://julialang.org"

# Analytics (optional)
google_analytics: UA-XXXXXXXX-X