name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Install CompatHelper
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'

      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If you use private registries or need SSH auth, set a repo secret and uncomment:
          # COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'

